### ISSUE TITLE
Tracking issue for the HTTP API

### ISSUE THREAD

**Issue by Arignir** [raven-os/nest-server#5]
In order to provide information about the packages that an instance of `nest-server` manages, it must be able to provide an HTTP API that third-party websites can use.

This API must be restful and provide routes to:

* [x] Retrieve packages' id given some filters (any metadata can be a filter) (ordering, limit and offset is mandatory to implement a proper paging system without doing it client-side)
* [x] Retrieve all metadatas for a package given it's id
* [x] Retrieve some status information, like up-time, number of packages etc.
